{
	"version": 1502688481,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/iplay-sheet0.png",
		"images/nomejogo-sheet0.png",
		"images/iinfo-sheet0.png",
		"images/iconfiguracao-sheet0.png",
		"images/ihomevitoria-sheet0.png",
		"images/parede-sheet0.png",
		"images/personagem-sheet0.png",
		"images/sensordevitoria-sheet0.png",
		"images/spritefonttempo.png",
		"images/grama1-sheet0.png",
		"images/grama2-sheet0.png",
		"images/grama3-sheet0.png",
		"images/grama4-sheet0.png",
		"images/grama5-sheet0.png",
		"images/grama6-sheet0.png",
		"images/placanome-sheet0.png",
		"images/play-sheet0.png",
		"images/configuracao-sheet0.png",
		"images/info-sheet0.png",
		"images/barreira-sheet0.png",
		"images/sensorplay-sheet0.png",
		"images/sensorconfiguracao-sheet0.png",
		"images/sensorinfo-sheet0.png",
		"media/pou - sky jump (menu).m4a",
		"media/pou - sky jump (menu).ogg",
		"media/sound effect - cartoon accent.m4a",
		"media/sound effect - cartoon accent.ogg",
		"media/table stroke sound effect.m4a",
		"media/table stroke sound effect.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}